plugins {
    id 'java'
}

group 'com.anma.ws'
version '0.0.2'

repositories {
    mavenCentral()
}

java {
    toolchain {
        version = JavaVersion.VERSION_25
    }
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.6.0'
    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation 'com.google.code.gson:gson:2.8.9'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}